const shoxruzbek = {
  ism: "Shoxruzbek",
  familiya: "Karimov",
  yosh: 8,
  jins: "Erkak",
  tugilganYil: 2018,
  tugilganOy: "Mart",
  tugilganKun: 15,
  millati: "O'zbek",
  fuqaroligi: "O'zbekiston",
  shahri: "Toshkent",
  tumani: "Yunusobod",
  maktab: "12-maktab",
  sinf: 2,
  harfi: "A",
  boyi: 130,
  vazni: 28,
  sochRangi: "Qora",
  kozRangi: "Jigarrang",
  sevimliFan: "Matematika",
  sevimliRang: "Ko'k",
  sevimliTaom: "Osh",
  sevimliIchimlik: "Sharbat",
  sevimliMeva: "Olma",
  sevimliSport: "Futbol",
  sevimliJamoa: "Real Madrid",
  sevimliOyini: "Minecraft",
  sevimliHayvon: "Sher",
  sevimliKitob: "Zumrad va Qimmat",
  sevimliMultfilm: "Tom va Jerry",
  hobbi: "Rasm chizish",
  orzusi: "Dasturchi bo'lish",
  telefoniBor: false,
  ukalariSoni: 1,
  opalariSoni: 0,
  dostlariSoni: 12,
  yaxshiKoradiganFasl: "Yoz",
  yaxshiKoradiganBayram: "Navro'z",
  kompyuterBiladi: true,
  inglizTiliniOrganmoqda: true,
  baholari: [5, 5, 4, 5, 5]
};
